insert into cuisines (name, id) values ('Japanese', 1);
insert into cuisines (name, id) values ('Chinese', 2);
insert into cuisines (name, id) values ('Italian', 3);
insert into restaurants (id, name, delivery_tax, cuisine_id) values (1, 'Hitaka food', 1.5, 1);
insert into restaurants (id, name, delivery_tax, cuisine_id) values (2, 'Aikiko', 2.5, 1);
insert into restaurants (id, name, delivery_tax, cuisine_id) values (3, 'Lee food', 2.5, 2);
insert into restaurants (id, name, delivery_tax, cuisine_id) values (4, 'Mamma mia', 2.5, 3);
insert into payment_types (id, description) values (1, 'CARD_DEBIT');
insert into payment_types (id, description) values (2, 'CARD_CREDIT');
insert into payment_types (id, description) values (3, 'PIX');
insert into payment_types (id, description) values (4, 'CASH');
insert into restaurant_payment_types (restaurant_id, payment_type_id) values (1, 1);
insert into restaurant_payment_types (restaurant_id, payment_type_id) values (1, 2);
insert into restaurant_payment_types (restaurant_id, payment_type_id) values (1, 3);
insert into restaurant_payment_types (restaurant_id, payment_type_id) values (1, 4);
insert into restaurant_payment_types (restaurant_id, payment_type_id) values (2, 4);
insert into restaurant_payment_types (restaurant_id, payment_type_id) values (3, 4);
insert into restaurant_payment_types (restaurant_id, payment_type_id) values (4, 3);
insert into restaurant_payment_types (restaurant_id, payment_type_id) values (4, 4);
